apiVersion: apps/v1
kind: Deployment
metadata:
  name: vistula-app-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: vistula-app
  template:
    metadata:
      labels:
        app: vistula-app
    spec:
      containers:
      - name: vistula-app-container
        image: manuel2oo3/my-cloud-app:v1 
        ports:
        - containerPort: 8080